--1 '축구의 역사'라는 도서의 출판사와 정가
SELECT PUBLISHER, PRICE, BOOKNAME FROM BOOK WHERE BOOKNAME = '축구의 역사';

--2 대한미디어 출판사에서 출판한 도서의 정보
SELECT * FROM BOOK WHERE PUBLISHER = '대한미디어';

--3 정가가 10000원 이하인 도서 정보
SELECT * FROM BOOK WHERE PRICE<=10000;

--4 김연아 고객의 전화번호
SELECT PHONE,NAME FROM CUSTOMER WHERE NAME='김연아';

--5 김연아 고객의 주소
SELECT ADDRESS, NAME FROM CUSTOMER WHERE NAME='김연아';

--6 김연아, 박지성 고객의 주소
SELECT ADDRESS, NAME FROM CUSTOMER WHERE NAME='박지성'OR NAME='김연아';
SELECT ADDRESS, NAME FROM CUSTOMER WHERE NAME IN('박지성', '김연아');

--7 도서 가격이 10000원 이상인 도서명과 출판사
SELECT BOOKNAME, PUBLISHER, PRICE FROM BOOK WHERE PRICE>=10000;

--8 출판사명 검색 (DISTINCT: 중복 제거)
SELECT DISTINCT PUBLISHER FROM BOOK;

--9 출판사명 검색 ALL - 생략가능
SELECT PUBLISHER FROM BOOK;
SELECT ALL PUBLISHER FROM BOOK;

--10 출판사순으로 도서정보 검색
SELECT * FROM BOOK ORDER BY PUBLISHER DESC;
--ASC : 오름차순(기본값), DESC : 내림차순
--조건없는 정렬은 WHERE 안씀

--11 출판사순, 가격순으로 도서정보
SELECT * FROM BOOK ORDER BY PUBLISHER, PRICE;

--12 출판사순, 가격순, 도서명순 도서정보
SELECT * FROM BOOK ORDER BY PUBLISHER, PRICE, BOOKNAME;

--13 모든 도서 정보를 출력
SELECT * FROM BOOK;

--14 도서명과 가격 검색
SELECT BOOKNAME, PRICE FROM BOOK;

--15 도서명과 출판사 검색
SELECT BOOKNAME, PUBLISHER FROM BOOK;

--16 출판사명을 한번씩만 검색
SELECT DISTINCT PUBLISHER FROM BOOK;

--17 대한미디어 출판사의 도서명만 검색
SELECT BOOKNAME,PUBLISHER FROM BOOK WHERE PUBLISHER='대한미디어';

--18 가격이 20000원 이상인 도서명과 가격 
SELECT BOOKNAME, PRICE FROM BOOK WHERE PRICE>=20000;

--19 도서가격이 10000원 이상 20000원 이하 도서 정보
SELECT * FROM BOOK WHERE PRICE>=10000 AND PRICE<=20000;
SELECT * FROM BOOK WHERE PRICE BETWEEN 10000 AND 20000;

--20 도서가격이 10000, 20000, 30000 인 도서 정보 
SELECT * FROM BOOK WHERE PRICE IN(10000,20000,30000);

--21 도서 가격이 NULL인 도서 정보 검색
SELECT * FROM BOOK WHERE PRICE IS NULL;
SELECT * FROM BOOK WHERE PRICE IS NOT NULL;

--22 도서 가격이 20000 미만인 도서 정보 
SELECT * FROM BOOK WHERE PRICE<20000;

--23 도서 가격이 20000미만이고 도서명이 축구의 역사인 도서 정보
SELECT * FROM BOOK WHERE PRICE<20000 AND BOOKNAME='축구의 역사';

--24 도서 가격이 20000미만이거나 도서명이 축구의 역사인 도서 정보
SELECT * FROM BOOK WHERE PRICE<20000 OR BOOKNAME='축구의 역사';

--25 출판사가 굿스포츠와 삼성당에서 나온 도서명과 출판사 검색
SELECT BOOKNAME, PUBLISHER FROM BOOK WHERE PUBLISHER IN('굿스포츠','삼성당');

--26  출판사가 굿스포츠와 삼성당이 아닌 출판사에서 나온 도서명과 출판사 검색
SELECT BOOKNAME, PUBLISHER FROM BOOK WHERE NOT PUBLISHER IN('굿스포츠','삼성당');
SELECT BOOKNAME, PUBLISHER FROM BOOK WHERE PUBLISHER NOT IN('굿스포츠','삼성당');

--27 도서 가격이 정해진 도서 정보 검색
SELECT * FROM BOOK WHERE PRICE IS NOT NULL;

--28 도서 가격이 10000미만, 20000 초과 도서 정보 검색
SELECT * FROM BOOK WHERE PRICE<10000 OR PRICE>20000;

--29 도서 가격이 20000원인 도서 정보 검색
SELECT * FROM BOOK WHERE PRICE=20000;

--30 도서 가격이 20000원이 아닌 도서 정보 검색
SELECT * FROM BOOK WHERE NOT PRICE=20000;
SELECT * FROM BOOK WHERE PRICE!=20000;

--31 '축구의 역사'를 출간한 출판사
SELECT PUBLISHER, BOOKNAME FROM BOOK WHERE BOOKNAME='축구의 역사';

--32 도서명에 '축구'가 포함된 출판사
SELECT PUBLISHER, BOOKNAME FROM BOOK WHERE BOOKNAME LIKE '%축구%';

--33 오늘 날짜 정보 확인
SELECT SYSDATE FROM DUAL;

--34 도서명이 '축구'로 시작하는 도서명 출력
SELECT BOOKNAME FROM BOOK WHERE BOOKNAME LIKE '축구%';

--35 출판사 명이 '대한'으로 시작하는 출판사에서 출간한 도서명과 출판사명
SELECT BOOKNAME, PUBLISHER FROM BOOK WHERE PUBLISHER LIKE '대한%';

--37 도서명의 두번째 글자가 '구'인 도서명 검색
SELECT BOOKNAME FROM BOOK WHERE SUBSTR(BOOKNAME, 2, 1)='구';
SELECT BOOKNAME FROM BOOK WHERE BOOKNAME LIKE '_구%';

--38 축구에 관한 도서 중 가격이 20000원 이상인 도서정보
SELECT * FROM BOOK WHERE BOOKNAME LIKE '%축구%' AND PRICE>=20000;
